<#import "parts/general.ftlh" as g>

<@g.general>
  <br>
  <br>
  <div>
    <button type="button" class="btn btn-success">
      <a href="/admin/create/product" style="text-decoration: none; color: white">Добавить продукт</a>
    </button>
    <button type="button" class="btn btn-success">
      <a href="/admin/create/user" style="text-decoration: none; color: white">Добавить пользователя</a>
    </button>
  </div>
  <br>
  <br>

  <div>

  </div>

</@g.general>