<#import "parts/general.ftlh" as g>

<@g.general styles=["/css/login.css"]>
    <div class="admin_main_block">
        <a href="/admin/create/product" class="btn btn-success">Добавить
            продукт</a>

        <a href="/#" class="btn btn-success">Добавить воронку продаж</a>

        <a href="/admin/create/user" class="btn btn-success">Добавить
            пользователя</a>

    </div>

</@g.general>